In [2]:
#co-relation coefficient:
import numpy as np

In [5]:
data=np.random.randint(1,10,(5,5))

In [15]:
data


array([[8, 8, 3, 7, 5],
       [4, 7, 6, 2, 8],
       [7, 2, 4, 1, 7],
       [5, 8, 1, 8, 8],
       [6, 4, 6, 4, 4]])

In [8]:
np.corrcoef(data)

array([[ 1.        , -0.35433072, -0.17454001,  0.63603088, -0.29475317],
       [-0.35433072,  1.        ,  0.39653955,  0.        , -0.15161961],
       [-0.17454001,  0.39653955,  1.        , -0.2046119 ,  0.4276686 ],
       [ 0.63603088,  0.        , -0.2046119 ,  1.        , -0.88852332],
       [-0.29475317, -0.15161961,  0.4276686 , -0.88852332,  1.        ]])

In [11]:
np.corrcoef(data).astype(int)

array([[1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
#defining a function

In [20]:
def greet():
    print("hello,world")

In [22]:
greet()

hello,world


In [43]:
def greet (arg):
    print (f"good morning,{arg}!")
greet("coders")

good morning,coders!


In [49]:
greet("ramya")

good morning,ramya!


In [ ]:
#return statement

In [61]:
def multiply(a,b,c):
    return a*b*c

result=multiply(3,5,4)
print(result)

60


In [63]:
multiply(3,4,9)

108

In [72]:
def division(a,b):
    return a/b

result=division(3,5)
print(result)

0.6


In [77]:
def add(*args):
    return sum(args)

print(add(1,2,3))
print(add(4,5,6,7,8))

6
30


In [81]:
def print_details(**kwargs):
    for key, value in kwargs.items():
        print(f"{key}:{value}")

print_details(name="alice",age =30,city="new york")

name:alice
age:30
city:new york


In [ ]:
#lamda functions


In [8]:
add =lambda a,b:a+b
print(add(8,5))

13


In [5]:
def add(a,b):
    return a+b
print(add(6,4))

10


In [9]:
multiply=lambda a,b:a*b
print(multiply(6,7))

42


In [ ]:
#creat a function to find square of a number

In [10]:
square = lambda x:x*x
print(square (5))

25


In [20]:
cube = lambda x:x*x*x
print(cube (5))

125


In [21]:
z=lambda x,y,:x-y
print(z(5,6))

-1


In [ ]:
#python arrays:

In [25]:
import array as ar

In [29]:
#creating an array

eg_array=ar.array('i',[1,2,3,4,5])