In [2]:
#multipilaction of numpy array
import numpy as np

In [6]:
array1 = np.array([[1,2,3],
                   [4,5,6]])
array2 = np.array([[7,8,9],
                  [10,11,12]])

product_array =array1*array2
print("multiplication:\n",product_array)

multiplication:
 [[ 7 16 27]
 [40 55 72]]


In [9]:
array1 = np.array([[1,2,3],
                   [4,6,8]])
array2 = np.array([1,4,6])

product_array =array1*array2
print("multiplication:\n",product_array)

multiplication:
 [[ 1  8 18]
 [ 4 24 48]]


In [ ]:
# matrix multiplication

In [46]:
x1=np.random.randint(0,10,(2,2))
x2=np.random.randint(0,10,(2,2))

In [47]:
x1

array([[7, 4],
       [3, 0]])

In [48]:
x2

array([[1, 9],
       [6, 2]])

In [49]:
np.dot(x1,x2)

array([[31, 71],
       [ 3, 27]])

In [51]:
x1=np.random.randint(0,10,(2,3))
x2=np.random.randint(0,10,(3,2))

In [52]:
x1

array([[0, 5, 2],
       [8, 0, 2]])

In [54]:
x2

array([[7, 9],
       [1, 8],
       [7, 9]])

In [55]:
np.dot(x1,x2)

array([[19, 58],
       [70, 90]])

In [ ]:
#string functions

In [57]:
x=np.array([1,2,3,'data'])

In [58]:
x

array(['1', '2', '3', 'data'], dtype='<U11')

In [60]:
np.char.capitalize(x)

array(['1', '2', '3', 'Data'], dtype='<U11')

In [61]:
np.char.center(x,10,fillchar='*')

array(['****1*****', '****2*****', '****3*****', '***data***'],
      dtype='<U10')

In [68]:
x=np.array([1,2,3,'data engineering'])

In [69]:
x

array(['1', '2', '3', 'data engineering'], dtype='<U16')

In [67]:
print(np.char.upper(x))
print(np.char.lower(x))
print(np.char.title(x))

['1' '2' '3' 'DATA ENGINEERING']
['1' '2' '3' 'data engineering']
['1' '2' '3' 'Data Engineering']


In [71]:
y=np.array(["data science","machine learning"])

In [78]:
np.char.split(y,sep='e')

array([list(['data sci', 'nc', '']), list(['machin', ' l', 'arning'])],
      dtype=object)

In [73]:
np.char.count(y,"a")

array([2, 2])

In [76]:
np.char.startswith(y,"d")

array([ True, False])

In [79]:
np.char.replace(y,'a','xxxxx')

array(['dxxxxxtxxxxx science', 'mxxxxxchine lexxxxxrning'], dtype='<U24')

In [80]:
np.char.rjust(y,20,fillchar="*")

array(['********data science', '****machine learning'], dtype='<U20')

In [ ]:
#time based functions

In [ ]:
#division of arrays

In [84]:
array1 = np.array([[10,34,56],
                   [34,65,67]])
array2 = np.array([[3,5,9],
                   [6,8,4]])
division_array=array1/array2
print("division:\n",division_array)
print(division_array.dtype)

division:
 [[ 3.33333333  6.8         6.22222222]
 [ 5.66666667  8.125      16.75      ]]
float64


In [ ]:
#calculating the exponential

In [85]:
a=np.array([1,2,3,4,5])
exp_a =np.exp(a)
print("orginal array:\n",a)

orginal array:
 [1 2 3 4 5]


In [86]:
#expo,sqrt,sin,cos, log
a=np.array([2,4,6])
print("sqrt of a:",np.sqrt(a))
print("exp of a:",np.exp(a))
print("sin of a:",np.sin(a))
print("cos of a:",np.cos(a))
print("log of a:",np.log(a))

sqrt of a: [1.41421356 2.         2.44948974]
exp of a: [  7.3890561   54.59815003 403.42879349]
sin of a: [ 0.90929743 -0.7568025  -0.2794155 ]
cos of a: [-0.41614684 -0.65364362  0.96017029]
log of a: [0.69314718 1.38629436 1.79175947]


In [ ]:
#aggregete functions

In [13]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
print("sum:",np.sum(a))
print("minimun value:",np.mean(a))
print("mean value:",np.median(a))
print("median value:",np.median(a))
print("corelation coeffient:",np.corrcoef(a))
print("standrand deviation :",np.std(a))


sum: 45
minimun value: 5.0
mean value: 5.0
median value: 5.0
corelation coeffient: 1.0
standrand deviation : 2.581988897471611
